FROM mcr.microsoft.com/playwright:v1.58.0-jammy

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ENV PLAYWRIGHT_BASE_URL=http://flux-explorer:42069
ENV CI=true

CMD ["npm","run","test:e2e:ui"]
